{{- if eq .Values.aiService.create true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-service-configs
data:
  AZURE_OPENAI_ENDPOINT: "{{ .Values.aiService.openAiEndpoint }}"
  AZURE_OPENAI_DEPLOYMENT_NAME: "{{ .Values.aiService.modelDeploymentName }}"
  USE_AZURE_OPENAI: "True"
  USE_AZURE_AD: "True"
  {{- /*
  If DALL-E model is used, set the model name
  */}}
  {{- if and .Values.aiService.openAiDalleEndpoint .Values.aiService.openAiDalleModelName }}
  AZURE_OPENAI_DALLE_ENDPOINT: "{{ .Values.aiService.openAiDalleEndpoint }}"
  AZURE_OPENAI_DALLE_DEPLOYMENT_NAME: "{{ .Values.aiService.openAiDalleModelName }}"
  AZURE_OPENAI_API_VERSION: "{{ .Values.aiService.azureOpenAiApiVersion }}"
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccount: ai-service
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ai-service
        image: {{ .Values.aiService.image.repository }}:{{ .Values.aiService.image.tag }}
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: ai-service-configs
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 3
          failureThreshold: 10
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          failureThreshold: 10
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: ai-service
{{- end }}