apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service
  annotations:
    azure.workload.identity/client-id: "{{ .Values.managedIdentityClientId }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: makeline-service
  annotations:
    azure.workload.identity/client-id: "{{ .Values.managedIdentityClientId }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  annotations:
    azure.workload.identity/client-id: "{{ .Values.managedIdentityClientId }}"